// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 后台-消费记录响应
 * @export
 * @interface ConsumeRecordResp
 */
export interface ConsumeRecordResp {
    /**
     * 申请ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    id?: number;
    /**
     * 消费单号
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    consumeNo?: string;
    /**
     * 会员ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    memberId?: number;
    /**
     * 会员卡号(暂时返回memberId)
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    cardNo?: string;
    /**
     * 卡类型ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    cardTypeId?: number;
    /**
     * 卡类型名称
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    cardTypeName?: string;
    /**
     * 会员姓名
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    memberName?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    phone?: string;
    /**
     * 身份证号
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    idCard?: string;
    /**
     * 本金余额(消费后余额)
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    balance?: number;
    /**
     * 赠送金余额(消费后余额)
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    giftBalance?: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    storeId?: number;
    /**
     * 门店名称
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    storeName?: string;
    /**
     * 房间ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    roomId?: number;
    /**
     * 房间号
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    roomNo?: string;
    /**
     * 房间名
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    roomName?: string;
    /**
     * 预定ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    reservationId?: number;
    /**
     * 申请业务员ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    applyStaffId?: number;
    /**
     * 申请业务员姓名
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    applyStaffName?: string;
    /**
     * 接待业务员ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    receptionStaffId?: number;
    /**
     * 接待业务员姓名
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    receptionStaffName?: string;
    /**
     * 消费金额
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    consumeAmount?: number;
    /**
     * 使用本金
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    useBalance?: number;
    /**
     * 使用赠送金
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    useGiftAmount?: number;
    /**
     * 状态
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    status?: ConsumeRecordRespStatusEnum;
    /**
     * 审核人ID
     * @type {number}
     * @memberof ConsumeRecordResp
     */
    reviewerId?: number;
    /**
     * 审核时间
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    reviewedAt?: string;
    /**
     * 驳回原因
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    rejectReason?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    remark?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof ConsumeRecordResp
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ConsumeRecordRespStatusEnum {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
    VOID = 'VOID'
}



