// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 会员响应
 * @export
 * @interface MemberResp
 */
export interface MemberResp {
    /**
     * 会员ID
     * @type {number}
     * @memberof MemberResp
     */
    id?: number;
    /**
     * 卡类型ID
     * @type {number}
     * @memberof MemberResp
     */
    cardTypeId?: number;
    /**
     * 卡类型名称
     * @type {string}
     * @memberof MemberResp
     */
    cardTypeName?: string;
    /**
     * 会员卡号
     * @type {string}
     * @memberof MemberResp
     */
    cardNo?: string;
    /**
     * 姓名
     * @type {string}
     * @memberof MemberResp
     */
    name?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof MemberResp
     */
    phone?: string;
    /**
     * 身份证号
     * @type {string}
     * @memberof MemberResp
     */
    idCard?: string;
    /**
     * 本金余额
     * @type {number}
     * @memberof MemberResp
     */
    balance?: number;
    /**
     * 赠送金余额
     * @type {number}
     * @memberof MemberResp
     */
    giftBalance?: number;
    /**
     * 累计充值
     * @type {number}
     * @memberof MemberResp
     */
    totalRecharge?: number;
    /**
     * 累计消费
     * @type {number}
     * @memberof MemberResp
     */
    totalConsume?: number;
    /**
     * 业务员ID
     * @type {number}
     * @memberof MemberResp
     */
    salesId?: number;
    /**
     * 业务员名称
     * @type {string}
     * @memberof MemberResp
     */
    salesName?: string;
    /**
     * 状态
     * @type {number}
     * @memberof MemberResp
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof MemberResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof MemberResp
     */
    updatedAt?: string;
}

