// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 会员门店业务员绑定响应
 * @export
 * @interface MemberBindingResp
 */
export interface MemberBindingResp {
    /**
     * 绑定ID
     * @type {number}
     * @memberof MemberBindingResp
     */
    id?: number;
    /**
     * 会员ID
     * @type {number}
     * @memberof MemberBindingResp
     */
    memberId?: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof MemberBindingResp
     */
    storeId?: number;
    /**
     * 业务员ID
     * @type {number}
     * @memberof MemberBindingResp
     */
    staffId?: number;
    /**
     * 备注
     * @type {string}
     * @memberof MemberBindingResp
     */
    remark?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof MemberBindingResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof MemberBindingResp
     */
    updatedAt?: string;
}


