// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 会员门店业务员绑定请求
 * @export
 * @interface MemberBindingReq
 */
export interface MemberBindingReq {
    /**
     * 会员ID
     * @type {number}
     * @memberof MemberBindingReq
     */
    memberId: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof MemberBindingReq
     */
    storeId: number;
    /**
     * 业务员ID
     * @type {number}
     * @memberof MemberBindingReq
     */
    staffId: number;
    /**
     * 备注
     * @type {string}
     * @memberof MemberBindingReq
     */
    remark?: string;
}


