// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 会员详情-充值记录响应
 * @export
 * @interface MemberRechargeRecordResp
 */
export interface MemberRechargeRecordResp {
    /**
     * 申请ID
     * @type {number}
     * @memberof MemberRechargeRecordResp
     */
    id?: number;
    /**
     * 充值单号
     * @type {string}
     * @memberof MemberRechargeRecordResp
     */
    applyNo?: string;
    /**
     * 本金充值金额
     * @type {number}
     * @memberof MemberRechargeRecordResp
     */
    amount?: number;
    /**
     * 赠送金充值金额
     * @type {number}
     * @memberof MemberRechargeRecordResp
     */
    giftAmount?: number;
    /**
     * 充值后本金余额
     * @type {number}
     * @memberof MemberRechargeRecordResp
     */
    balance?: number;
    /**
     * 充值后赠送金余额
     * @type {number}
     * @memberof MemberRechargeRecordResp
     */
    giftBalance?: number;
    /**
     * 备注
     * @type {string}
     * @memberof MemberRechargeRecordResp
     */
    remark?: string;
    /**
     * 审核时间(实际入账时间)
     * @type {string}
     * @memberof MemberRechargeRecordResp
     */
    reviewedAt?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof MemberRechargeRecordResp
     */
    createdAt?: string;
}


