// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 会员详情-消费记录响应
 * @export
 * @interface MemberConsumeRecordResp
 */
export interface MemberConsumeRecordResp {
    /**
     * 申请ID
     * @type {number}
     * @memberof MemberConsumeRecordResp
     */
    id?: number;
    /**
     * 消费单号
     * @type {string}
     * @memberof MemberConsumeRecordResp
     */
    consumeNo?: string;
    /**
     * 消费金额
     * @type {number}
     * @memberof MemberConsumeRecordResp
     */
    consumeAmount?: number;
    /**
     * 消费后本金余额
     * @type {number}
     * @memberof MemberConsumeRecordResp
     */
    balance?: number;
    /**
     * 消费后赠送金余额
     * @type {number}
     * @memberof MemberConsumeRecordResp
     */
    giftBalance?: number;
    /**
     * 消费类型(推断)
     * @type {string}
     * @memberof MemberConsumeRecordResp
     */
    consumeType?: string;
    /**
     * 备注
     * @type {string}
     * @memberof MemberConsumeRecordResp
     */
    remark?: string;
    /**
     * 审核时间(实际扣减时间)
     * @type {string}
     * @memberof MemberConsumeRecordResp
     */
    reviewedAt?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof MemberConsumeRecordResp
     */
    createdAt?: string;
}


