// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 房间创建/更新请求
 * @export
 * @interface RoomReq
 */
export interface RoomReq {
    /**
     * 门店ID
     * @type {number}
     * @memberof RoomReq
     */
    storeId: number;
    /**
     * 房间名称
     * @type {string}
     * @memberof RoomReq
     */
    roomName: string;
    /**
     * 房号
     * @type {string}
     * @memberof RoomReq
     */
    roomNo?: string;
    /**
     * 房型
     * @type {string}
     * @memberof RoomReq
     */
    roomType?: string;
    /**
     * 房间价格
     * @type {number}
     * @memberof RoomReq
     */
    price?: number;
    /**
     * 状态
     * @type {number}
     * @memberof RoomReq
     */
    status?: number;
}


