// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 房间响应
 * @export
 * @interface RoomResp
 */
export interface RoomResp {
    /**
     * 房间ID
     * @type {number}
     * @memberof RoomResp
     */
    id?: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof RoomResp
     */
    storeId?: number;
    /**
     * 房名
     * @type {string}
     * @memberof RoomResp
     */
    roomName?: string;
    /**
     * 房号
     * @type {string}
     * @memberof RoomResp
     */
    roomNo?: string;
    /**
     * 房型
     * @type {string}
     * @memberof RoomResp
     */
    roomType?: string;
    /**
     * 房间价格
     * @type {number}
     * @memberof RoomResp
     */
    price?: number;
    /**
     * 状态
     * @type {number}
     * @memberof RoomResp
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof RoomResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof RoomResp
     */
    updatedAt?: string;
}


