// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 门店响应
 * @export
 * @interface StoreResp
 */
export interface StoreResp {
    /**
     * 门店ID
     * @type {number}
     * @memberof StoreResp
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof StoreResp
     */
    name?: string;
    /**
     * 编码
     * @type {string}
     * @memberof StoreResp
     */
    code?: string;
    /**
     * 城市
     * @type {string}
     * @memberof StoreResp
     */
    city?: string;
    /**
     * 地址
     * @type {string}
     * @memberof StoreResp
     */
    address?: string;
    /**
     * 状态
     * @type {number}
     * @memberof StoreResp
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof StoreResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof StoreResp
     */
    updatedAt?: string;
}


