// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 门店创建/更新请求
 * @export
 * @interface StoreReq
 */
export interface StoreReq {
    /**
     * 门店名称
     * @type {string}
     * @memberof StoreReq
     */
    name: string;
    /**
     * 门店编码
     * @type {string}
     * @memberof StoreReq
     */
    code?: string;
    /**
     * 城市
     * @type {string}
     * @memberof StoreReq
     */
    city?: string;
    /**
     * 地址
     * @type {string}
     * @memberof StoreReq
     */
    address?: string;
    /**
     * 状态
     * @type {number}
     * @memberof StoreReq
     */
    status?: number;
}


